---
deployment:
  tasks:
    - export DEPLOYPATH=/home/danilaud/shuna.danilaudza.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp docs.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp image $DEPLOYPATH